namespace Winnerino
{
    [default_interface]
    runtimeclass AdditionalSettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        AdditionalSettingsPage();

        Boolean TransparencyControlsEnabled{ get; };
    }
}
