namespace Winnerino
{
    [bindable]
    [default_interface]
    runtimeclass DriveSearchModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        DriveSearchModel(String driveName);
    Boolean IsSelected{ get; set; };
    String DriveName{ get; };
    }
}
