namespace Winnerino
{
    [bindable]
    [default_interface]
    runtimeclass DriveViewModel : Windows.Foundation.IStringable
    {
        DriveViewModel();
        String Name;
        String FriendlyName;
    }
}
