namespace Winnerino
{
    [default_interface]
    runtimeclass FileLargeView : Microsoft.UI.Xaml.Controls.UserControl
    {
        FileLargeView();
        FileLargeView(String path, Boolean isFile);
        FileLargeView(Windows.Storage.StorageFile file);

        Boolean IsDirectory{ get; };
        String FilePath{ get; };
    }
}
