namespace Winnerino
{
    [default_interface]
    runtimeclass FileLargeView : Microsoft.UI.Xaml.Controls.UserControl
    {
        FileLargeView();

        Windows.Foundation.IAsyncAction Initialize(String path, Boolean isFile);

        String FileName{ get; };
        String FilePath{ get; };
        Boolean IsDirectory{ get; };
    }
}
