namespace Winnerino
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        static Winnerino.MainWindow Current{ get; };
        Windows.Foundation.Size Size{ get; };
        Windows.Graphics.PointInt32 Position{ get; };
        Microsoft.UI.WindowId Id{ get; };

        void NotifyUser(String message, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity);
        void NotifyError(Int32 code);
        void NotifyError(Int32 code, String additionalMessage);
        void ChangeTheme(Microsoft.UI.Xaml.ElementTheme theme);
        Boolean NavigateTo(Windows.UI.Xaml.Interop.TypeName typeName);
        Boolean NavigateTo(Windows.UI.Xaml.Interop.TypeName typeName, IInspectable parameter);
        void GoBack();

        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Window, Microsoft.UI.Xaml.ElementTheme> ThemeChanged;
    }
}
