namespace Winnerino
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        static Winnerino.MainWindow Current{ get; };

        void notifyUser(String message, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity);
    }
}
