namespace Winnerino
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        static Winnerino.MainWindow Current{ get; };

        void NotifyUser(String message, Microsoft.UI.Xaml.Controls.InfoBarSeverity severity);
        void NotifyError(Int32 code);
        void NotifyError(Int32 code, String additionalMessage);
        void ChangeTheme(Microsoft.UI.Xaml.ElementTheme theme);
    }
}
