namespace Winnerino
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        Windows.Foundation.Uri GithubUri{ get; };

        String getCompactModeTooltip();
    }
}
