namespace Winnerino
{
    [default_interface]
    runtimeclass SystemHealthView : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SystemHealthView();
        
        Double SystemGeneralHealth{ get; set; };
        Microsoft.UI.Xaml.Media.Brush SystemGeneralForeground{ get; };
        Double TotalUsedSpace{ get; set; };
        Microsoft.UI.Xaml.Media.Brush TotalUsedForeground{ get; };
    }
}
